# Generated by Django 5.1.4 on 2024-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('experimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('responsavel', models.CharField(max_length=100)),
                ('trafego', models.IntegerField()),
                ('amostras', models.IntegerField()),
            ],
        ),
    ]
