# Generated by Django 5.1.4 on 2024-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_experimento_amostras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='amostras',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='experimento',
            name='trafego',
            field=models.IntegerField(default=0),
        ),
    ]
