# Generated by Django 5.1.4 on 2024-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experimento_amostras_experimento_trafego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='trafego',
            field=models.IntegerField(default=100),
        ),
    ]
